QALI-321 Create scenario examples for Jakarta EE Messaging
qalipsis/qalipsis-plugin-jakarta-ee-messaging pull request #4
Opened 2023-02-23 10:04 UTC by Alexey-Prudnikov

2023-03-02 08:53 UTC, Alexey-Prudnikov commented on jakarta-ee-messaging/src/main/kotlin/io/qalipsis/plugins/jakarta/producer/JakartaProducer.kt
> +                    //I understand how to work with the blocking queue here
*don't understand

2023-09-15 14:59 UTC, ericjesse requested changes

2023-09-15 14:59 UTC, ericjesse commented on jakarta-ee-messaging/docker-compose.yml
Remove this file, only testContainers should be used for testing.

2023-09-15 14:59 UTC, ericjesse commented on jakarta-ee-messaging/src/test/kotlin/io/qalipsis/plugins/jakarta/consumer/JakartaConsumerConverterIntegrationTest.kt
> -    val testDispatcherProvider = TestDispatcherProvider()
Revert that change.

2023-09-19 05:50 UTC, merged